/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

/**
 *
 * @author Shavinda
 */
public class BInformation extends javax.swing.JFrame {

    /**
     * Creates new form SupplyManagement
     */
    public BInformation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_B_Information = new javax.swing.JPanel();
        lbl_BID = new javax.swing.JLabel();
        lbl_Ohours = new javax.swing.JLabel();
        lbl_Bname = new javax.swing.JLabel();
        lbl_address = new javax.swing.JLabel();
        lbl_Cno = new javax.swing.JLabel();
        btn_Exit = new javax.swing.JButton();
        btn_Back = new javax.swing.JButton();
        lbl_Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel_B_Information.setLayout(null);

        lbl_BID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_BID.setText("Branch  ID        :  CM002");
        jPanel_B_Information.add(lbl_BID);
        lbl_BID.setBounds(210, 120, 240, 30);

        lbl_Ohours.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_Ohours.setText("Opening Hours :   Sample_TEXT");
        jPanel_B_Information.add(lbl_Ohours);
        lbl_Ohours.setBounds(210, 360, 260, 30);

        lbl_Bname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_Bname.setText("Branch  Name   :  Sample_TEXT");
        jPanel_B_Information.add(lbl_Bname);
        lbl_Bname.setBounds(210, 180, 240, 30);

        lbl_address.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_address.setText("Address             :   Sample_TEXT");
        jPanel_B_Information.add(lbl_address);
        lbl_address.setBounds(210, 240, 260, 30);

        lbl_Cno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_Cno.setText("Contact No       :   Sample_TEXT");
        jPanel_B_Information.add(lbl_Cno);
        lbl_Cno.setBounds(210, 300, 260, 30);

        btn_Exit.setBackground(new java.awt.Color(153, 0, 0));
        btn_Exit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Exit.setForeground(new java.awt.Color(255, 255, 255));
        btn_Exit.setText("Exit");
        jPanel_B_Information.add(btn_Exit);
        btn_Exit.setBounds(20, 470, 190, 40);

        btn_Back.setBackground(new java.awt.Color(204, 204, 255));
        btn_Back.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Back.setForeground(new java.awt.Color(0, 0, 51));
        btn_Back.setText("Back");
        jPanel_B_Information.add(btn_Back);
        btn_Back.setBounds(210, 470, 190, 40);

        lbl_Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/M8.jpg"))); // NOI18N
        jPanel_B_Information.add(lbl_Background);
        lbl_Background.setBounds(-6, -6, 710, 530);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_B_Information, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_B_Information, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BInformation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Back;
    private javax.swing.JButton btn_Exit;
    private javax.swing.JPanel jPanel_B_Information;
    private javax.swing.JLabel lbl_BID;
    private javax.swing.JLabel lbl_Background;
    private javax.swing.JLabel lbl_Bname;
    private javax.swing.JLabel lbl_Cno;
    private javax.swing.JLabel lbl_Ohours;
    private javax.swing.JLabel lbl_address;
    // End of variables declaration//GEN-END:variables
}
